name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      COC_CHARA_SHEET_FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test
      - name: Deploy firebase
        run: |
          docker-compose -f ./deploy-compose.yml build
          docker-compose -f ./deploy-compose.yml run deploy
      - name: Slack Notification
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: "Deploy to Firebase"
          mention: "here"
          mention_if: "failure"
          channel: "#labs"
          username: "CoC CharaSheet"
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
